const API=(window.KAMAI_API||'').replace(/\/$/,'');let token=localStorage.getItem('kamai_token');let loginMode=false;
const $=id=>document.getElementById(id);function showAuth(){ $('auth').hidden=false;$('dashboard').hidden=true; }function showDash(){ $('auth').hidden=true;$('dashboard').hidden=false; }
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(opts.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d;}
$('switchAuth').onclick=()=>{loginMode=!loginMode;$('authTitle').textContent=loginMode?'Login':'Create account';$('authBtn').textContent=loginMode?'Login':'Register';$('name').style.display=loginMode?'none':'';$('switchAuth').textContent=loginMode?'Create a new account':'I already have an account';$('msg').textContent='';};
$('authBtn').onclick=async()=>{try{$('msg').textContent='Working...';const body=loginMode?{email:$('email').value,password:$('password').value}:{name:$('name').value,email:$('email').value,password:$('password').value};const d=await api(loginMode?'/api/auth/login':'/api/auth/register',{method:'POST',body:JSON.stringify(body)});token=d.token;localStorage.setItem('kamai_token',token);await load();}catch(e){$('msg').textContent=e.message;}};
async function load(){try{const d=await api('/api/me');$('balance').textContent=d.user.coins;$('welcome').textContent='Welcome, '+d.user.name+'!';showDash();const t=await api('/api/tasks');$('tasks').innerHTML=t.tasks.map(x=>`<div class="task"><b>${x.title}</b><p>Reward: ${x.reward} coins</p><button ${x.completed?'disabled':''} data-task="${x.id}">${x.completed?'Completed':'Complete'}</button></div>`).join('');document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>complete(b));}catch(e){localStorage.removeItem('kamai_token');token=null;showAuth();$('msg').textContent='Backend connection/login required.';}}
async function complete(b){try{b.disabled=true;const d=await api('/api/tasks/'+b.dataset.task+'/complete',{method:'POST'});$('balance').textContent=d.coins;b.textContent='Completed';}catch(e){alert(e.message);b.disabled=false;}}
$('logout').onclick=()=>{localStorage.removeItem('kamai_token');token=null;showAuth();};$('withdraw').onclick=()=>alert('Withdrawal module is the next production step. No real withdrawal is enabled yet.');
if(token)load();else showAuth();
