const express=require('express');
const cors=require('cors');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const {Pool}=require('pg');
const path=require('path');
const app=express();
const PORT=process.env.PORT||3000;
const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME';
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
app.use(cors());app.use(express.json());
app.use(express.static(path.join(__dirname,'..','public')));
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,coins INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS tasks(id SERIAL PRIMARY KEY,title TEXT NOT NULL,reward INTEGER NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE);CREATE TABLE IF NOT EXISTS task_completions(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),task_id INTEGER NOT NULL REFERENCES tasks(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,task_id));CREATE TABLE IF NOT EXISTS ledger(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),type TEXT NOT NULL,coins INTEGER NOT NULL,note TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);const c=await pool.query('SELECT COUNT(*)::int c FROM tasks');if(c.rows[0].c===0)await pool.query('INSERT INTO tasks(title,reward) VALUES ($1,$2),($3,$4)',['Daily Check-in',10,'Visit Sponsor Offer',25]);}
function auth(req,res,next){try{const t=(req.headers.authorization||'').replace('Bearer ','');req.user=jwt.verify(t,JWT_SECRET);next()}catch{res.status(401).json({error:'Unauthorized'})}}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'Kamai backend'}));
app.post('/api/auth/register',async(req,res)=>{const{name,email,password}=req.body||{};if(!name||!email||!password||password.length<6)return res.status(400).json({error:'Name, email and 6+ character password required'});try{const hash=await bcrypt.hash(password,10);const q=await pool.query('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email,coins',[name.trim(),email.trim().toLowerCase(),hash]);const u=q.rows[0];const token=jwt.sign({id:u.id},JWT_SECRET,{expiresIn:'7d'});res.json({token,user:u})}catch{res.status(409).json({error:'Email already registered'})}});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body||{};const q=await pool.query('SELECT * FROM users WHERE email=$1',[(email||'').trim().toLowerCase()]);const u=q.rows[0];if(!u||!(await bcrypt.compare(password||'',u.password_hash)))return res.status(401).json({error:'Invalid email or password'});const token=jwt.sign({id:u.id},JWT_SECRET,{expiresIn:'7d'});res.json({token,user:{id:u.id,name:u.name,email:u.email,coins:u.coins}})});
app.get('/api/me',auth,async(req,res)=>{const q=await pool.query('SELECT id,name,email,coins,created_at FROM users WHERE id=$1',[req.user.id]);res.json({user:q.rows[0]})});
app.get('/api/tasks',auth,async(req,res)=>{const q=await pool.query('SELECT t.id,t.title,t.reward,CASE WHEN tc.id IS NULL THEN 0 ELSE 1 END completed FROM tasks t LEFT JOIN task_completions tc ON tc.task_id=t.id AND tc.user_id=$1 WHERE t.active=true ORDER BY t.id',[req.user.id]);res.json({tasks:q.rows})});
app.post('/api/tasks/:id/complete',auth,async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const t=(await client.query('SELECT * FROM tasks WHERE id=$1 AND active=true',[req.params.id])).rows[0];if(!t)throw Object.assign(new Error('Task not found'),{status:404});const exists=await client.query('SELECT id FROM task_completions WHERE user_id=$1 AND task_id=$2',[req.user.id,t.id]);if(exists.rowCount)throw Object.assign(new Error('Task already completed'),{status:409});await client.query('INSERT INTO task_completions(user_id,task_id) VALUES($1,$2)',[req.user.id,t.id]);await client.query('UPDATE users SET coins=coins+$1 WHERE id=$2',[t.reward,req.user.id]);await client.query('INSERT INTO ledger(user_id,type,coins,note) VALUES($1,$2,$3,$4)',[req.user.id,'task_reward',t.reward,t.title]);await client.query('COMMIT');const u=(await pool.query('SELECT coins FROM users WHERE id=$1',[req.user.id])).rows[0];res.json({ok:true,coins:u.coins,reward:t.reward})}catch(e){await client.query('ROLLBACK');res.status(e.status||400).json({error:e.message})}finally{client.release()}});
app.get('/api/ledger',auth,async(req,res)=>{const q=await pool.query('SELECT id,type,coins,note,created_at FROM ledger WHERE user_id=$1 ORDER BY id DESC LIMIT 100',[req.user.id]);res.json({ledger:q.rows})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'..','public','index.html')));
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('Kamai live-ready on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
